name: org_parser
description: A pure-Dart parser for Emacs Org Mode (https://orgmode.org) markup
version: 10.0.3
homepage: https://github.com/amake/org_parser

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  petitparser: ^7.0.1
  functional_zipper: ^0.0.2
  more: ^4.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.12.0
  collection: ^1.0.0
